## Introduction to Altair (part 1)

In this section, we will focus on getting some basic ideas of Altair and getting familiar about how to generate basic figures with it. Also, we still discuss how to change the graphical marks and encoding channels in Altair.

In [1]:
#pip install altair

In [2]:
# Install the module
import pandas as pd
import altair as alt

In [3]:
# Import a data from vega-datasets
from vega_datasets import data  # import vega_datasets
cars = data.cars()              # load cars data as a Pandas data frame
cars.head()

,Name,Miles_per_Gallon,Cylinders,Displacement,Horsepower,Weight_in_lbs,Acceleration,Year,Origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,1970-01-01,USA
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,1970-01-01,USA
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,1970-01-01,USA
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,1970-01-01,USA
4,ford torino,17.0,8,302.0,140.0,3449,10.5,1970-01-01,USA

#### Fundamental object: Chart

The fundamental object in Altair is the Chart, which takes a data frame as a single argument.

#### Marks and Encodings

We first indicate what kind of mark (geometric shape) we want to use to represent the data.

##### Define types of the attributes

Different type of attributes may lead to different data visualization. 

- ':N' indicates a nominal type (unordered, categorical data),
- ':O' indicates an ordinal type (rank-ordered data),
- ':Q' indicates a quantitative type (numerical data with meaningful magnitudes), and
- ':T' indicates a temporal type (date/time data)

##### Data Transformation: Aggregation and Filter

You can generate plot of summary statistics without calculating it. The options include: 

- sum
- average
- median
- q1,q3
- min,max

You can also include filter to exclude any part of the data or use calculate to generate new attribute to plot.

#### Title and labels

#### Exercise

The iris dataset contains the length and width of sepals and petals for three flower species. We will load this dataset using vega_datasets.

In [4]:
# Load the iris dataset
iris = data.iris()

# Display the first few rows of the dataset
iris.head()

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

Let’s create a basic scatter plot to visualize the relationship between petalLength and petalWidth. Then we will apply a transformation to normalize the petalLength and petalWidth before encoding them into a scatter plot. Normalizing data can help in comparing features that have different scales.

**Check in today** 
Copy your code to: https://tinyurl.com/37482xxu

In [ ]:
alt.Chart(iris).transform_calculate(
    norm_petalLength = '(datum.petalLength - 3.75)/(1.76)',
    norm_petalWidth = '(datum.petalWidth - 1.2)/(0.76)'
).mark_point().encode(
    alt.X('norm_petalLength:Q', title = 'Normalized Petal Length'),
    alt.Y('norm_petalWidth:Q', title = 'Normalized Petal Width')
).properties(
    title = "Normalized petal length vs. Width")

#### Choices of mark and encoding

###### Encoding Channels

- x: Horizontal (x-axis) position of the mark.
- y: Vertical (y-axis) position of the mark.
- size: Size of the mark. May correspond to area or length, depending on the mark type.
- color: Mark color, specified as a legal CSS color.
- opacity: Mark opacity, ranging from 0 (fully transparent) to 1 (fully opaque).
- shape: Plotting symbol shape for point marks.
- tooltip: Tooltip text to display upon mouse hover over the mark.
- order: Mark ordering, determines line/area point order and drawing order.
- column: Facet the data into horizontally-aligned subplots.
- row: Facet the data into vertically-aligned subplots.

###### Marks

- mark_point() - Scatter plot points with configurable shapes.
- mark_circle() - Scatter plot points as filled circles.
- mark_square() - Scatter plot points as filled squares.
- mark_tick() - Vertical or horizontal tick marks.
- mark_bar() - Rectangular bars.
- mark_boxplot() - Boxplot
- mark_line() - Connected line segments.
- mark_area() - Filled areas defined by a top-line and a baseline.
- mark_rect() - Filled rectangles, useful for heatmaps.
- mark_rule() - Vertical or horizontal lines spanning the axis.
- mark_text() - Scatter plot points represented by text.

#### Adding multiple plots together and save

#### Save the plot -- HTML